import { View, Text, Dimensions, StatusBar, StyleSheet } from "react-native";
import React from "react";

export default StyleSheet.create({
  Container: {
    flex: 1,
    padding: 40,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    backgroundColor: "#242424",
  },
  statusbar: {
    flex: 1,
    height: StatusBar.currentHeight,
    backgroundColor: "#242424",
  },
  button: {
    position: "absolute",
    height: 60,
    top: Dimensions.get("window").height - 80,
    left: Dimensions.get("window").width - 80,
    width: 60,
    backgroundColor: "#DE2851",
    borderRadius: 40,
  },
  buttonTxt: {
    fontSize: 40,
    textAlign: "center",
    fontWeight: "normal",
    fontFamily: "Roboto",
    color: "white",
  },
  shadow: {
    shadowColor: "#DE2851",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,

    elevation: 2,
  },
  header: {
    position: "absolute",
    fontStyle: "italic",
    marginTop: 20,
    fontSize: 30,
    padding: 5,
    left: 15,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalView: {
    width: 350,
    height: 230,
    margin: 20,
    backgroundColor: "#242424",
    borderRadius: 20,
    padding: 35,
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalBtn: {
    width: "80%",
    borderRadius: 10,
    padding: 10,
    elevation: 2,
  },
  buttonClose: {
    backgroundColor: "#DE2851",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    color: "white",
    fontSize: 20,
    textAlign: "left",
  },
  modalTextInput: {
    backgroundColor: "#222222",
    color: "whitesmoke",
    borderRadius: 10,
    height: 48,
    width: 320,
    marginBottom: 15,
    padding: 10,
    textAlign: "left",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonClr: {
    position: "absolute",
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    top: Dimensions.get("window").height - 80,
    right: Dimensions.get("window").width - 150,
    width: 120,
    backgroundColor: "#DE2851",
    borderRadius: 20,
  },
  buttonClrTxt: {
    fontSize: 30,
    textAlign: "center",
    fontWeight: "normal",
    fontFamily: "Roboto",
    color: "white",
  },
});
